### ISSUE TITLE
Falta realizar una limpieza y re-estructuración del código mapGeneration

### ISSUE THREAD

**Issue by Wauro21** [Wauro21/elo328#1]
El almacenamiento de los valores leídos desde archivos .csv/.track , es algo engorrosa, la clase añadida BidimensionalMatrix, podría ser una buena opción para seguir, sin embargo, falta mejorar la integración o buscar una mejor manera de almacenar los valores.  ✓

**Comment by Wauro21** [comment]
1. Limpiar y unificar mapGeneration, estandarizar el uso de algun arreglo/vector para guardar los valores y no hacer cambios redundantes. ✓
2. Implementar codigo rotación y centrado de la pista, con offset para despues.  ✓ 
3. Obtener la distancia transversal de la pista.  ✓
4. Calibrar extensión máxima en vertical (Ymax) donde la proyección tiene sentido.  ✓
5. Calcular distancia en la máscara  ✓
6. Calcular la distancia desde los puntos de la pista (en memoria)  ✓

**Comment by Wauro21** [comment]
El código de rotación de la pista, necesita probarse, al parecer tendría un problema ✓

**Comment by Zimrahin** [comment]
falta calibrar la distancia en pixeles vs la distancia en metros de la pista almacenada ✓ (distancia encontrada de 40 m mediante Google Earth en Silverstone)

**Comment by Zimrahin** [comment]
Implementar línea de carreras en la máscara. ✓

**Comment by Zimrahin** [comment]
Falta calibrar nuevamente y arreglar problemas con -1 en getDistances() ✓

**Comment by Zimrahin** [comment]
calibrar offset de la posición del auto (sumar o restar 2 metros)  ✓
edit: el offset calculado experimentalmente es de 2.64 metros  (la ubicación que entrega la telemetría se encuentra centrada detrás del piloto) ✓

**Comment by Zimrahin** [comment]
comprobar similitud de línea de carreras del juego vs mapa

**Comment by Zimrahin** [comment]
- Hacer manual de compilación
- Unificar código en un solo main, que funcione tanto con vídeo como con imágenes. Este debe incluir lectura de archivo .csv cuyos datos están escritos previamente con un código en Python.

**Comment by Zimrahin** [comment]
eliminar plotSilverstone cuando nos hayamos asegurado de la funcionalidad del proyecto unido ✓
