### ISSUE TITLE
Re-estructuración git

### ISSUE THREAD

**Issue by felipeville** [Wauro21/elo328#2]
Re-ordenar los códigos del repositorio para dejar un módulo por carpeta, con sus respectivos `.h` y `.cpp` junto con una función _global_ del módulo para luego ser llamada desde el exterior. Esto a modo de orden y consistencia con el documento de diseño.

Además, dejar un "módulo" `main.cpp` aparte para ir probando lo que se lleva hasta ahora de la funcionalidad completa del proyecto.

**Comment by felipeville** [comment]
Listo:
- Módulo UDP
- Módulo Proyección
- Módulo Detección

---
Se eliminó v2 y v3 de F1_Detection, debido a que v4 anterior contenía todo lo anterior.

**Comment by Wauro21** [comment]
Procedo a cerrar el Issue, referencia commit: cb9ea4b23c1dcfa821dff58d405b491f6bd75ee6
