### ISSUE TITLE
Problemas informe

### ISSUE THREAD

**Issue by Zimrahin** [Wauro21/elo328#3]
-debemos ser más explícitos en los excel (no poner como encargado "equipo")
-no debemos borrar nada del git, porque cuenta como trabajo "fracasado", y debemos explicitar en el informe por qué decidimos no usarlos

**Comment by felipeville** [comment]
Deje la versión anterior de la detección como 'F1_Detection [Versión Antigua]'

**Comment by Zimrahin** [comment]
preguntarle al profe a qué se refiere con alcance

**Comment by Zimrahin** [comment]
Debemos mejorar del informe:
-ESTADO DEL ARTE Y TÉCNICA. (se nos fue corregirlo para el hito 2)
-REQUISITOS DE INTERFACES 
-FALTAS DE ORTOGRAFÍA: se tomará, se identificará, de por UDP, la puerta abierto
-Debemos ser más "atómicos". Segmentar más las tareas (por ejemplo, como lo hemos hecho en ISSUES).

**Comment by nabway** [comment]
> preguntarle al profe a qué se refiere con alcance
Cito la plantilla del profe
[Describa el módulo en términos generales, incluyendo cómo calza dentro del sistema. No explique las partes del módulo (ejemplo, funciones, estructuras de datos etc.), sino más bien cómo el módulo se presenta en la arquitectura del sistema. Es decir, cómo se ve la arquitectura desde el punto de vista del módulo.]

**Comment by steevglez** [comment]
Revisado y corregido el punto del informe sobre ESTADO DEL ARTE Y TÉCNICA

**Comment by Wauro21** [comment]
> > preguntarle al profe a qué se refiere con alcance
> > Cito la plantilla del profe
> > [Describa el módulo en términos generales, incluyendo cómo calza dentro del sistema. No explique las partes del módulo (ejemplo, funciones, estructuras de datos etc.), sino más bien cómo el módulo se presenta en la arquitectura del sistema. Es decir, cómo se ve la arquitectura desde el punto de vista del módulo.]

Si, el problema es que no entendemos por qué a que se refiere con eso, como corregirlo para que cumpla con lo pedido

**Comment by Zimrahin** [comment]
Recordar adjuntar fotos en la descripción de cada módulo

**Comment by steevglez** [comment]
Sobre el punto de alcance, el profesor explico: "Se refiere a cómo se relaciona el módulo con otros módulos/partes del sistema (con qué módulos interactúa), que es lo que entra y sale (flujos de información) en esta relación (general) y qué es lo que hace en forma general."

**Comment by steevglez** [comment]
Revisado y corregido el punto del informe sobre REQUISITOS DE INTERFACES

**Comment by felipeville** [comment]
Cierro issue: Informe para el Hito 3 terminado.
