### ISSUE TITLE
Funciones getDistances() y minDistance()

### ISSUE THREAD

**Issue by Zimrahin** [Wauro21/elo328#4]
getDistances(): (Diego)
Se debe agregar condición de seguridad a la función getDistances() para cuando la pista no termine en la parte superior de la imagen. Esto ocurre cuando hay una curva o el automóvil no apunta en dirección paralela a la pista. Para obtener esta condición en código, basta con evaluar uno de los polinomios y determinar si se encuentra en las dimensiones horizontales de la pista. Se adjunta imagen.
![getdistances](https://user-images.githubusercontent.com/38572720/102719335-4565e780-42cc-11eb-960c-a4738ee9a735.png)

minDistances(): (Sebastián)
Esta función no nos sirve en su estado actual puesto que de funcionar con el set de puntos de una pista solo encontraría la distancia "mínima" a los bordes. Lo que se debe lograr, es encontrar la distancia EN EL EJE DE LAS ABSCISAS. ¿Por qué?. Encontrar la distancia mínima solo ayuda a mapear en el caso de que la pista sea idealmente paralela al eje de las ordenadas (eje Y). Al igual que para el problema de getDistances(), se deben considerar las curvas. Se adjunta una imagen explicativa de lo que haría el código (en caso de funcionar) vs lo que debe hacer para el mapeo correcto de puntos.
![mindistances](https://user-images.githubusercontent.com/38572720/102719452-04220780-42cd-11eb-8f5f-2e3388766981.png)

**Comment by Zimrahin** [comment]
Solucionado getDistances() 
commit: 08101451dcf1830577ed5e392de522caf27dd7a5

**Comment by Wauro21** [comment]
Se corrige la funcionalidad de min distance, se rehace la función en mapGeneration.cpp/.h , falta calibrar comparando con ambas funcionas, para obtener m/px. Commit solucion: 684d111b3b30f2058a66b73807595bfc6a421add


Unicamente para cerrar este issue falta testear

**Comment by Wauro21** [comment]
Listo el testeo de la funcion manyDistances() - Se cierra issue
