### ISSUE TITLE
Cambiar funcionalidad de la función manyDistances() <Map generation>

### ISSUE THREAD

**Issue by Wauro21** [Wauro21/elo328#5]
Cambiar la funcionalidad, para que entregue en porcentaje la distancia de uno de los límites con la línea de carrera

**Comment by Zimrahin** [comment]
Implementación  y calibración lista para cálculo de ancho de la pista, tanto en imagen como en el mapa. Falta modificar las funciones para que den un porcentaje de la ubicación transversal de la línea de carreras.

**Comment by Wauro21** [comment]
Se adapta la función para que retorne un porcentaje de la distancia desde el borde externo. Commit 7cd2a7cfaea392cfab3ed07819ef66342a0efd80
